spring:
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/spring_r2dbc_samples?sslMode=DISABLED
    username: root
    password: 123456
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: debug
